language: rust
matrix:
  allow_failures:
    - rust: nightly
  include:
  # Stable
  - rust: stable
    os: linux
  - rust: stable
    os: osx
  - rust: stable
    os: windows
  # Beta
  - rust: beta
    os: linux
  - rust: beta
    os: osx
  - rust: beta
    os: windows
  # Nightly
  - rust: nightly
    os: linux
  - rust: nightly
    os: osx
  - rust: nightly
    os: windows
  # Minimum version
  - rust: 1.37.0
    os: linux
    script:
      - cargo make ci-flow
  - rust: 1.37.0
    os: osx
    script:
      - cargo make ci-flow
  - rust: 1.37.0
    os: windows
    script:
      - cargo make ci-flow
  # Deploy jobs
  - env: DEPLOY=1
    os: osx
    script:
      - cargo make zip-release-ci-flow --env TARGET=x86_64-apple-darwin
  - env: DEPLOY=1
    os: windows
    script:
      - cargo make zip-release-ci-flow --env TARGET=x86_64-pc-windows-msvc
  - env: DEPLOY=1
    os: linux
    script:
      - cargo make zip-release-ci-flow --env TARGET=x86_64-unknown-linux-musl
    addons:
      apt:
        packages:
        - musl-tools
before_script:
  - cargo install --debug cargo-make
script:
  - cargo run --bin cargo-make --target-dir target/ci -- make ci-flow
deploy:
  provider: releases
  api_key:
    secure: U5ziHSOtcXHe7XX1KdEIIVVbOd/AKMvXquYoS2GJnnil3gxGRarOGkZ/F3iFGEzccXwNPuvhnBwSciVMx/Rsx4gl6ET8bila8T4/AppRhORBM4RBfAweJVZUibDoGzQVjc9Y4Aeo2E2oy8yMNFAh8WLu9tY4v5x/hlgUmffW88j3Mg6EdJb5rMQZ0aqyuTzJm6XvDixQQLaJ1bjONFAG7eRQzfs+TC/wiDXipm2bs/wcLcCl/GeB3KDyT7GH1dkeyChwdVt2rqiQM2N7gwSVKZsiV9ZFcv4SFRdwl/W2FKSAlNeIF68qXA4OAaWQxWIlfHqUk6iYgzCA8XbFIFDgRFjFvLEP5fK8Ul5gsOCZF6D9hSDYXvFvbPEqqaOKJUlxZrOaID8+j64E5gI5cPMGlYG4OPkqRYvx/NsES4OUhkrfr8j2wFAUqBPrBqCOnbp1PUkLFoQGRxy28gudhoHPjfPYcFokNErriwz4HG05UBIeGQzUKLNynxVFrwMN8u8UxOh6TDMmOa+okWLcn0jnZPTTi7zCtz34G4ltE/ikL5ERK0tV/lyvqbI6PXQfpW1mXVWf00pfkW88vXaE/uYlOdHU3FnpcGV4nynpniIvk0VJ78Fp/g2cwxw4QTMb6rIjwxmH0Dl9s1aiU/fNHnm/6vE46dwdOdykj1Uim0XgVmw=
  file_glob: true
  file: "*.zip"
  on:
    condition: $DEPLOY = 1
    tags: true
  skip_cleanup: true
  overwrite: true
