[package]
name = "cargo-make"
version = "0.19.1"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
documentation = "https://sagiegurari.github.io/cargo-make"
homepage = "https://sagiegurari.github.io/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/CHANGELOG.md",
    "/Makefile.toml"
]

[lib]
name = "cli"
path = "src/lib/mod.rs"

[[bin]]
name = "cargo-make"
path = "src/main.rs"

[[bin]]
name = "makers"
path = "src/makers.rs"

[dependencies]
ci_info = "^0.6"
clap = "^2.32"
colored = "^1.7"
dirs = "^1.0"
envmnt = "^0.3"
fern = "^0.5"
glob = "^0.3"
indexmap = { version = "^1.0", features = ["serde-1"] }
log = "^0.4"
rand = "^0.6"
run_script = "^0.3"
rust_info = "^0.2"
semver = "^0.9"
serde = "^1.0"
serde_derive = "^1.0"
shell2batch = "^0.3"
toml = "^0.5"

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/cargo-make"

[badges.appveyor]
repository = "sagiegurari/cargo-make"
service = "github"
branch = "master"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
