[package]
name = "cargo-make"
version = "0.32.0"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
edition = "2018"
documentation = "https://sagiegurari.github.io/cargo-make"
homepage = "https://sagiegurari.github.io/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["command-line-utilities", "development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/CHANGELOG.md",
    "/Makefile.toml"
]

[lib]
name = "cli"
path = "src/lib/mod.rs"

[[bin]]
name = "cargo-make"
path = "src/main.rs"

[[bin]]
name = "makers"
path = "src/makers.rs"

[dependencies]
ci_info = "^0.10"
clap = "^2"
colored = "^2"
dirs = "^3"
duckscript = "^0.5"
duckscriptsdk = "^0.6"
envmnt = "^0.8.2"
fern = "^0.6"
fsio = { version = "^0.1.2", features = ["temp-path"] }
git_info = "^0.1.2"
glob = "^0.3"
home = "^0.5"
indexmap = { version = "^1", features = ["serde-1"] }
serde_json = "^1"
log = "^0.4"
run_script = "^0.6"
rust_info = "^0.3.1"
semver = "^0.10"
serde = "^1"
serde_derive = "^1"
shell2batch = "^0.4"
toml = "^0.5"

[dev-dependencies]
rusty-hook = "^0.11"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
