[package]
name = "cargo-make"
version = "0.15.0"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
documentation = "https://sagiegurari.github.io/cargo-make"
homepage = "https://sagiegurari.github.io/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/CHANGELOG.md",
    "/Makefile.toml"
]

[dependencies]
ci_info = "^0.2.0"
clap = "^2.32.0"
dirs = "^1.0.4"
fern = "^0.5.7"
glob = "^0.2.11"
indexmap = { version = "^1.0.2", features = ["serde-1"] }
log = "^0.4.6"
rand = "^0.5.5"
run_script = "^0.2.0"
rust_info = "^0.2.0"
semver = "^0.9.0"
serde = "^1.0.80"
serde_derive = "^1.0.80"
shell2batch = "^0.2.2"
toml = "^0.4.8"

[features]
default = []

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/cargo-make"

[badges.appveyor]
repository = "sagiegurari/cargo-make"
service = "github"
branch = "master"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
